[workspace]

members = [
    "bottomless",
    "bottomless-cli",
    "sqlc",
    "sqld",
    "sqld-libsql-bindings",
    "testing/end-to-end",
]

[workspace.dependencies]
libsql = { version = "0.1.6", default-features = false }
