[workspace]

members = [
    "bottomless",
    "bottomless-cli",
    "sqlc",
    "sqld",
    "sqld-libsql-bindings",
    "testing/end-to-end",
]

[workspace.dependencies]
rusqlite = { version = "0.29.0", git = "https://github.com/psarna/rusqlite", rev = "3d2fc88a1", default-features = false, features = [
    "buildtime_bindgen",
    "bundled-libsql-wasm-experimental",
    "column_decltype",
    "load_extension"
] }
