[workspace]

members = [
    "bottomless",
    "bottomless-cli",
    "sqld",
    "sqld-libsql-bindings",
]

[workspace.dependencies]
rusqlite = { version = "0.29.0", git = "https://github.com/tursodatabase/rusqlite.git", rev = "a72d529", default-features = false, features = [
    "buildtime_bindgen",
    "bundled-libsql-wasm-experimental",
    "column_decltype",
    "load_extension",
    "modern_sqlite"
] }

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.2.0-prerelease.6"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "libsql/homebrew-sqld"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin"]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether cargo-dist should create a Github Release or use an existing draft
create-release = false

# TODO(lucio): Remove this once tonic has released a new version with fixes
[patch.crates-io]
tonic = { git = "https://github.com/hyperium/tonic" }
tonic-build = { git = "https://github.com/hyperium/tonic" }
console-api = { git = "https://github.com/tokio-rs/console", branch = "lucio/tonic-fix" }
libsql = { git = "https://github.com/libsql/libsql.git", rev = "61b4f5b" }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"


